name: smadaras-page

on: [push]

env:
  # Setting an environment variable with the value of a configuration variable
  ENV_VAR: ${{ vars.ENV_VAR }}
  ENV_STATIC: Static

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python -c "import sys; print(sys.version)"
